import type { FC, SVGProps } from "react";
import {
  BracketsBlue,
  BracketsYellow,
  CLang,
  Clojure,
  CodeOrange,
  Cplus,
  Dart,
  Docker,
  Document,
  Elixir,
  Erlang,
  Exe,
  Git,
  Go,
  Graphql,
  Haskell,
  Java,
  Js,
  Kotlin,
  Lock,
  Lua,
  Markdown,
  Perl,
  PHP,
  Python,
  R,
  Reactjs,
  Reactts,
  Ruby,
  Rust,
  Sass,
  Scala,
  Shell,
  Svelte,
  Swift,
  TypeScript,
  Vue,
  XML,
  Yaml,
} from "@react-symbols/icons";

const FILE_ICON_MAP: Record<string, FC<SVGProps<SVGSVGElement>>> = {
  js: Js,
  mjs: Js,
  jsx: Reactjs,
  ts: TypeScript,
  tsx: Reactts,
  json: BracketsYellow,
  css: BracketsBlue,
  scss: Sass,
  sass: Sass,
  html: CodeOrange,
  htm: Document,
  md: Markdown,
  mdx: Markdown,
  yml: Yaml,
  yaml: Yaml,
  xml: XML,
  lock: Lock,
  gitignore: Git,
  rs: Rust,
  py: Python,
  java: Java,
  c: CLang,
  cpp: Cplus,
  cc: Cplus,
  cxx: Cplus,
  go: Go,
  php: PHP,
  rb: Ruby,
  vue: Vue,
  svelte: Svelte,
  dart: Dart,
  swift: Swift,
  kt: Kotlin,
  kts: Kotlin,
  sh: Shell,
  bash: Shell,
  zsh: Shell,
  dockerfile: Docker,
  sql: Document,
  graphql: Graphql,
  gql: Graphql,
  r: R,
  scala: Scala,
  clj: Clojure,
  cljs: Clojure,
  hs: Haskell,
  ex: Elixir,
  exs: Elixir,
  erl: Erlang,
  hrl: Erlang,
  lua: Lua,
  pl: Perl,
  exe: Exe,
};

export function getFileIcon(fileName: string): FC<SVGProps<SVGSVGElement>> {
  const extension = fileName.split(".").pop()?.toLowerCase() || "";
  return FILE_ICON_MAP[extension] || Document;
}

